In [1]:
import numpy as np

In [6]:
a = np.array([10,11,12,13,14,15]) #одномерный массив
a

array([10, 11, 12, 13, 14, 15])

In [12]:
b = np.array([[16,17,18],[19,20,21]]) #двумерный массив
b

array([[16, 17, 18],
       [19, 20, 21]])

In [15]:
a = np.zeros((3,5)) #двумерный массив из нулей 3x5 
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
b = np.ones((4,5)) #двумерный массив из единиц 3x5 
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones((2,3,5)) #трехмерный массив из единиц размер 3x3x5 

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [20]:
np.eye(4) #единичная матрица 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.arange(10,50,10) #создание массива с помощью arange

array([10, 20, 30, 40])

In [30]:
a.shape

(3, 5)

In [31]:
b.dtype

dtype('float64')

In [37]:
a = np.arange(15)**2

In [41]:
a[4] #выведем элемент с индексом 4

np.int64(16)

In [45]:
a[3:7] #выведем элементы с 3 по 6 включительно

array([ 9, 16, 25, 36])

In [46]:
a[[3,7]]

array([ 9, 49])

In [49]:
a[[7,3]]

array([49,  9])

In [51]:
c = a[2:6] #получение подмассива с помощь среза
c

array([ 4,  9, 16, 25])

In [56]:
b = np.arange(15)

In [58]:
c = a*b #поэлементное умножение 2 массивов
c

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [61]:
с = a+b #поэлементное сложение 2 массивов
c

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [64]:
np.mean(a) #вычисление средней величины с помощью mean

np.float64(67.66666666666667)

In [66]:
np.median(a) #вычисление медианы с помощью median

np.float64(49.0)

In [69]:
np.var(a) #вычисление дисперсии с помощью var

np.float64(3933.6888888888884)